server:
  port: 8001


spring:
  application:
    name: micro_servie_dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: micro_servie_dept8001
    prefer-ip-address: true

info:
  app.name: tianzhen-microservicecloud
  company.name: www.tianzhen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


